import { OrderStatuses } from "../enums/order-statuses";

export class Order {
    id: string; // primary key autogenerated
    userId: string;
    tableNumber: number
    status: OrderStatuses;
    amount: number;
    createdAt: Date; // auto generated
    updatedAt: Date; // auto generated
}