import { Roles } from "../enums/roles";

export class User {
    id: string; // primary key (autogenerated)
    email: string;
    passwordHash: string; // hashed password
    firstName: string;
    lastName: string;
    role: Roles;
    createdAt: Date; // auto generated
    updatedAt: Date; // auto updated
}