export class CooporateCard {
    id: string; // primary key autogenerated
    userId: string;
    cardNumber: string; // encrypted
    cardToken: string;
    balance: number;
    createdAt: Date;
    updatedAt: Date;
}